language: python
dist: bionic

# 3.6 is listed first so it gets used for the later build stages
python:
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  # SpatiaLite needed for the --load-extension test:
  - sudo apt-get update
  - sudo apt-get -y install libsqlite3-mod-spatialite

script:
  - pip install -U pip wheel
  - pip install .[test]
  # Only run the numpy/pandas tests on Python 3.7:
  - python -c "import sys; print(sys.version_info.minor == 7)" | grep True > /dev/null && pip install pandas || true
  - pytest

cache:
    directories:
      - $HOME/.cache/pip

jobs:
  include:
    - stage: release tagged version
      if: tag IS present
      language: python
      python: 3.6
      script:
        - pip install -U pip wheel
      deploy:
        - provider: pypi
          user: simonw
          distributions: sdist bdist_wheel
          password: ${PYPI_PASSWORD}
          on:
            branch: main
            tags: true
            repo: simonw/sqlite-utils
